
package systemaconcesionario;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;


public class PanelControl extends javax.swing.JFrame {
    static boolean esAdministrador = false;
    public PanelControl(boolean isAdmin) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        esAdministrador = isAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        clienteBtn = new javax.swing.JMenu();
        vehiculoBtn = new javax.swing.JMenu();
        polizasBtn = new javax.swing.JMenu();
        tipoPoliza = new javax.swing.JMenu();
        sucursalBtn = new javax.swing.JMenu();
        vendedorBtn = new javax.swing.JMenu();
        accidentesBtn = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Desktop.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        clienteBtn.setText("Clientes");
        clienteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(clienteBtn);

        vehiculoBtn.setText("Vehículos");
        vehiculoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehiculoBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(vehiculoBtn);

        polizasBtn.setText("Polizas");
        polizasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                polizasBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(polizasBtn);

        tipoPoliza.setText("Tipo");
        tipoPoliza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoPolizaMouseClicked(evt);
            }
        });
        jMenuBar1.add(tipoPoliza);

        sucursalBtn.setText("Sucursales");
        sucursalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sucursalBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(sucursalBtn);

        vendedorBtn.setText("Vendedor");
        vendedorBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendedorBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(vendedorBtn);

        accidentesBtn.setText("Accidentes");
        accidentesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accidentesBtnMouseClicked(evt);
            }
        });
        jMenuBar1.add(accidentesBtn);

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void position (JInternalFrame frame) {
        int x = (Desktop.getWidth() / 2) - (frame.getWidth()/2);
        int y = (Desktop.getHeight() / 2) - (frame.getHeight()/2);
        frame.setLocation(x, y);

    }
    
    boolean frameExists(JInternalFrame frame) {
        JInternalFrame[] areActives=Desktop.getAllFrames();
        boolean exists=false;  
        if(areActives.length == 0) {
             return exists;
        }
        
        if(areActives.length > 0) {    
            for (int i=0; i < areActives.length; i++) {
                if(areActives[i]!=frame){
                    exists=true;                 
                }
            }
            return exists;
        }
        
        return exists;
    }
    
    
    private void clienteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteBtnMouseClicked
        Clientes clientes = new Clientes(); 
            if (!frameExists(clientes)){
                Desktop.add(clientes);
                position(clientes);
                clientes.setVisible(true);
            } 
    }//GEN-LAST:event_clienteBtnMouseClicked

    
    private void vehiculoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiculoBtnMouseClicked
         Vehiculos vehiculos = new Vehiculos();
            if (!frameExists(vehiculos)){
                Desktop.add(vehiculos);
                position(vehiculos);
                vehiculos.setVisible(true);
            } 
    }//GEN-LAST:event_vehiculoBtnMouseClicked

    private void accidentesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accidentesBtnMouseClicked
         Accidentes accidentes = new Accidentes();
            if (!frameExists(accidentes)){
                Desktop.add(accidentes);
                position(accidentes);
                accidentes.setVisible(true);
            } 
    }//GEN-LAST:event_accidentesBtnMouseClicked

    private void vendedorBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendedorBtnMouseClicked
        if(esAdministrador){         
            Vendedor vendedor = new Vendedor();
            if (!frameExists(vendedor)){
                Desktop.add(vendedor);
                position(vendedor);
                vendedor.setVisible(true);
            } 
        } else {
            JOptionPane.showMessageDialog(null,
                "Acceso solo para administrador",
                "Atención",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_vendedorBtnMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        InicioSesion login = new InicioSesion();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void sucursalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sucursalBtnMouseClicked
        if(esAdministrador){ 
            Sucursales sucursales = new Sucursales();
            if (!frameExists(sucursales)){
                Desktop.add(sucursales);
                position(sucursales);
                sucursales.setVisible(true);
            } 
        } else {
            JOptionPane.showMessageDialog(null,
                "Acceso solo para administrador",
                "Atención",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_sucursalBtnMouseClicked

    private void polizasBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polizasBtnMouseClicked
        Polizas polizas = new Polizas();
        if (!frameExists(polizas)){
            Desktop.add(polizas);
            position(polizas);
            polizas.setVisible(true);
        }
    }//GEN-LAST:event_polizasBtnMouseClicked

    private void tipoPolizaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoPolizaMouseClicked
        if(esAdministrador){ 
            TipoPolizas tipo_polizas = new TipoPolizas();
            if (!frameExists(tipo_polizas)){
                Desktop.add(tipo_polizas);
                position(tipo_polizas);
                tipo_polizas.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                "Acceso solo para administrador",
                "Atención",
                JOptionPane.ERROR_MESSAGE
            );  
        }
    }//GEN-LAST:event_tipoPolizaMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl(true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu accidentesBtn;
    private javax.swing.JMenu clienteBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu polizasBtn;
    private javax.swing.JMenu salir;
    private javax.swing.JMenu sucursalBtn;
    private javax.swing.JMenu tipoPoliza;
    private javax.swing.JMenu vehiculoBtn;
    private javax.swing.JMenu vendedorBtn;
    // End of variables declaration//GEN-END:variables
}
